### ISSUE TITLE
STklos reader gets confused with illegal escape sequences in strings

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#152]
If I try to enter the string `"\x9 +"` STklos correctly sigals an error, but interprets the rest of the string as if it were input to be read and evaluated:

```
stklos> "\x9 +"
**** Error:
%read: bad inline hexa sequence (9  1) on port `#[input-virtual-port 7f45d77140b0]'
	(type ",help" for more information)
#[primitive +]
stklos>                       ;; I entred ^D here!
**** Error:
%read: end of file while reading a string on `#[input-virtual-port 7f45d77140b0]'
	(type ",help" for more information)
```

The same for `" \xo "`...

Found it while porting SRFI-207.

**Comment by jpellegrini** [comment]
I found it.
When the error is signalled, the reader gets out without finishing reading until the closing `"` or `EOF`.
I can send a PR whcih fixes this along with SRFI-207.

**Comment by jpellegrini** [comment]
I actually sent the PR for this issue only, without SRFI-207, because there is a small issue with that SRFI that I still have to fix (it is related to error signalling and `%claim-error` -- I'm working on it.

**Comment by egallesio** [comment]
Hi @jpellegrini 

I think that I have corrected this issue. However, I have not used the code of PR #153 because it didn't worked when the string also contained a quote after the error (something like `" an error  \x12    and now a quote \" and the end"`? Furthermore, the code entered  in a loop when the hexa sequence was used in a symbol (this is the same function that was used for parsing  hexa sequence for strings and symbols). 

Anyways, I used the tests that were in your PR (thanks for that) and added a couple of tests for hexadecimal sequences in symbols.

I let you close this issue if it is correct for you.

**Comment by jpellegrini** [comment]
That's great! I'll see if all goes well later when I get back to porting SRFI-207.

**Comment by jpellegrini** [comment]
@egallesio  see this:

```
stklos> "\xf"
                       <== STklos waits until I type another "
"
**** Error:
%read: bad inline hexa sequence (f") in a string
```

**Comment by egallesio** [comment]
This should be fixed this time  (hope so ...)

**Comment by jpellegrini** [comment]
Indeed, it's fixed! :)
