### ISSUE TITLE
Information on download page

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#18]
Hi @egallesio !

On the download page, 1.31 is still listed as the latest version, although 1.40 is out. And the link to "source distribution" also points to 1.31.

One other thing: there are also two links, one to gitlab and one to github. Is one of those preferred? If so, maybe it would be nice to mention it there.

**Comment by egallesio** [comment]
Oops, There was a bug in my script to update the web site. This is corrected now. Thanks to have signaled this issue.

About the preferred git repository, my preference would have been gitlab, but since github seems more used, I suppose that activity on STklos will be more visible if I stick with github and have a copy tree on gitlab. Anyway, all the pushes are synchronized and the trees are the same. 
Information on the download page should be clearer now.

**Comment by lassik** [comment]
> About the preferred git repository, my preference would have been gitlab, but since github seems more used, I suppose that activity on STklos will be more visible if I stick with github and have a copy tree on gitlab.

This is correct, for better or worse.
