### ISSUE TITLE
Build fails when not connected to a terminal

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#2]
I'm trying to make a Docker container from the latest STklos release. `make` does not work if I have no terminal (i.e. running the Linux shell command `tty` says `not a tty`). `docker build` cannot provide a terminal, so would it be OK to change the build to work without one?

I tried running make as `ptyrun make` (the ptyrun command comes from the ptyget package and allocates a pseudo-tty) but that produces the following error:

```
Making all in utils
make[1]: Entering directory '/build/stklos/utils'
./tmpcomp stklos-compile.stk stklos-compile
#[condition &error-message 94734647094464]: bad string `#f'
**** FATAL ERROR: no handler present!
ABORT
make[1]: *** [Makefile:521: stklos-compile] Error 1
make[1]: Leaving directory '/build/stklos/utils'
```

In every configuration I tried, it's the `stklos-compile` command that fails.

**Comment by lassik** [comment]
Hunch: is `#f` expected to be the tty name, which it does not have in this case? `ptyrun tty` does say `/dev/pts/0`. I think `tty` gets its tty device from stdin.

**Comment by egallesio** [comment]
> I'm trying to make a Docker container from the latest STklos release. `make` does not work if I have no terminal (i.e. running the Linux shell command `tty` says `not a tty`). `docker build` cannot provide a terminal, so would it be OK to change the build to work without one?
> 
> I tried running make as `ptyrun make` (the ptyrun command comes from the ptyget package and allocates a pseudo-tty) but that produces the following error:
> 
> ```
> Making all in utils
> make[1]: Entering directory '/build/stklos/utils'
> ./tmpcomp stklos-compile.stk stklos-compile
> #[condition &error-message 94734647094464]: bad string `#f'
> **** FATAL ERROR: no handler present!
> ABORT
> make[1]: *** [Makefile:521: stklos-compile] Error 1
> make[1]: Leaving directory '/build/stklos/utils'
> ```
> 
> In every configuration I tried, it's the `stklos-compile` command that fails.

A docker version would be definitively interesting. I don't know why you have such a problem with make. Are you trying to compile version which is actually in the current tree (the NO handler present message make me think this is not the case, since this is something that should be repaired now). 
Anyway, the tmcomp is a simple shell script. Can you execute it with some traces. What is the shell which is used in your environment? 
The only dependence to be or not on a tty in STklos code seems to be in fport.c (which can be bypassed by the --interactive option to the stklos command. Can you add it in the stklos call in tpccomp? 
If you can send me your dockerfile, i can try to see (even if I'm a noob in docker).

**Comment by egallesio** [comment]
> Hunch: is `#f` expected to be the tty name, which it does not have in this case? `ptyrun tty` does say `/dev/pts/0`. I think `tty` gets its tty device from stdin.

Can you tell me how do you see that the tty name is #f? Thanks.

**Comment by lassik** [comment]
Thanks for responding! Here's the exact Docker configuration we have: https://github.com/weinholt/scheme-docker/tree/stklos-wip/stklos I can explore more later.

**Comment by lassik** [comment]
> Can you tell me how do you see that the tty name is #f? Thanks.

I'm not sure that it is. That was just a thought about one possibility to investigate. It came from this: `#[condition &error-message 94734647094464]: bad string `#f'`

**Comment by egallesio** [comment]
> Thanks for responding! Here's the exact Docker configuration we have: https://github.com/weinholt/scheme-docker/tree/stklos-wip/stklos I can explore more later.

I have made a container running STklos by adding the --interactive flag when running stklos during build (for making the documentation and for compiling some scripts). I have not used ptyrun dor that. Anyway, the problem is definitively due to the fact that we don't have a pty when building a container. I have tried to tackle down further why it is a problem when we are building a container and only in this case.  Launching make with a nohup (or with the at command) is OK even if we don't have a pty associated. For now, I search a better solution than forcing the interactive mode for running stklos during the construction of the image. 
To be continued.

**Comment by lassik** [comment]
Sounds good, thank you for investigating this! Can you share a patch for the build scripts that runs the builds using `--interactive`? We can create the container using that patch, and when the problem is solved for real, we can remove the patch.

**Comment by egallesio** [comment]
I have finally found where the problem comes from. Itt was not a problem of missing pty. It took me some time, because IMHO debugging a docker build is not so easy. The problem comes form a query to the TERM variable which is not defined during the docker build. 

A simple correction to the Dockerfile could be to use
    RUN env TERM="dumb" make all install
to build STklos (of course, next version of STklos, will correct this bug and this workaround will not be necessary anymore) 

I have also put a modified Dockerfile which links to libreadline to have a command line editor and avoid to use a tool such as rlwrap. I also force stklos to run with utf8 encoding. It is available at 
https://gist.github.com/egallesio/3c45fca4dd76b589874cc0a5ad0e8aad

**Comment by lassik** [comment]
Wow, so it turned out to be a much simpler issue :) That's great.

I put the following build commands into the Dockerfile to be as close to the standard `./configure && make && make install` as possible:

```
RUN TERM=dumb make
RUN make install
```

`make install` works fine even without `TERM`.

The final Dockerfile is here: https://github.com/weinholt/scheme-docker/tree/stklos

> I have also put a modified Dockerfile which links to `libreadline` to have a command line editor and avoid to use a tool such as `rlwrap`. I also force stklos to run with utf8 encoding.

These are very nice additions, thank you for them!

> debugging a docker build is not so easy

Did you know that you can get a shell in any intermediate container, not just the final one? `docker run -it 79c0e248ce01 bash` -- replace `79c0e248ce01` with any of the checksums from the `docker build` output. That makes it easy to examine the file system and re-run build commands to find out exactly what went wrong.

**Comment by egallesio** [comment]
> Wow, so it turned out to be a much simpler issue :) That's great.
> 
> I put the following build commands into the Dockerfile to be as close to the standard `./configure && make && make install` as possible:
> 
> ```
> RUN TERM=dumb make
> RUN make install
> ```
> 
> `make install` works fine even without `TERM`.
> 
> The final Dockerfile is here: https://github.com/weinholt/scheme-docker/tree/stklos
> 
> > I have also put a modified Dockerfile which links to `libreadline` to have a command line editor and avoid to use a tool such as `rlwrap`. I also force stklos to run with utf8 encoding.
> 
> These are very nice additions, thank you for them!
> 
> > debugging a docker build is not so easy
> 
> Did you know that you can get a shell in any intermediate container, not just the final one? `docker run -it 79c0e248ce01 bash` -- replace `79c0e248ce01` with any of the checksums from the `docker build` output. That makes it easy to examine the file system and re-run build commands to find out exactly what went wrong.

Yes I have seen that, bug when running inside the container, we have a pty and the TERM variable is defined, so the bug does not appear!!!

**Comment by lassik** [comment]
You're right. I had the same problem when trying to look into this bug.
