### ISSUE TITLE
SRFI-1 x STklos make-list behavior

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#24]
Hello.
It seems that STklos make-list is not consistent with SRFI-1's `make-list`:
```
stklos> (make-list 3)
(#void #void #void)
stklos> (load "srfi-1")
stklos> (make-list 3)
(#f #f #f)
stklos>
```
Not a problem for most practical purposes. But... I have ported  SRFI-51 to STklos (still did not make the pull request, but it's mostly ready) -- and then there is this problem:
- since SRFI-51 uses append-reverse, which is in SRFI-1, but not in plain STklos, I required "srfi-1" in SRFI-51;
- but when I run the tests, all SRFI-51 tests pass, but the R7RS tests fail: 

```
==== Testing R7RS  ...                                           failed
Errors found in this section:
test make-list.1 on (make-list 3) expected (#void #void #void) but got (#f #f #f)
```

So... What would be the best thing to do?

- change STklos behavior, so `(make-list k)` returns `(#f #f ... #f)`
- change the R7RS tests
- avoid adding SRFI-51 for now

**Comment by egallesio** [comment]
Hi @jpellegrini,
Another solution could be to modify the srfi-1 implementation so that it returns #void (which probably didn't exist when I have  ported SRFI-1 (or even suppress it from SRFI-1 since it is R7RS now) 

R7RS states:  .... Otherwise the initial contents of each element is unspecified.
SRFI-1 states: ....  If the fill argument is not given, the elements of the list may be arbitrary values. 

I have tested the behavior of `make-lisp` on some Scheme implementations I have on my laptop (without loading any library):
| Implementation    | default value                   |
| ----------------- | ------------------------------- |
| Bigloo            | #unspecified                    |
| Chez              | #&lt;void&gt;                         |
| Chibi             | #undef                          |
| Chicken           | error (make-list is undefined)    |
| Cyclone           | #f                              |
| Gambit            | 0                               |
| Gauche            | #f                              |
| Guile             | ()                              |
| Racket            | error (need a second parameter) |
| STklos            | #void                           |

It seems that the special value denoting the unspecified value (or void) is preferred (4 on the 8 which implement `make-list`). It seems also to be more in phase with R7RS (without contradicting SRFI-1). 

What do you think?

**Comment by lassik** [comment]
If STklos supports a void/unspecified value, that one is probably the best choice.

`#f` is also fine, but as you say, it would be to use the same one for the RnRS and SRFI 1 versions.

**Comment by jpellegrini** [comment]
Ok - I'll look into changing the SRFI-1 implementation.

By the way -- Chicken needs "`import (srfi 1))`" before using make-list, and it uses #f:
```
#;1> (import (srfi 1))
; loading /home/jeronimo/pkg/scheme/chicken/ROOT-git/lib/chicken-git/11/srfi-1.import.so ...

Note: re-importing already imported identifier: assoc

Note: re-importing already imported identifier: member
; loading /home/jeronimo/pkg/scheme/chicken/ROOT-git/lib/chicken-git/11/srfi-1.so ...
#;2> (make-list 3)
(#f #f #f)
```

**Comment by jpellegrini** [comment]
It was actually a one-liner! I have included it in the pull request (did a git force-push, the PR now has two commits).

**Comment by jpellegrini** [comment]
Commit 7f0550e31d99783c35a43465a8377974815dd938 fixes this; is it OK to close the issue now?

**Comment by egallesio** [comment]
Yes, it can be closed.
However,  I will rework this SRFI since I have seen are some more incoherence now that some functions it defines are in R7RS.

**Comment by jpellegrini** [comment]
Ok, closing!
