### ISSUE TITLE
Compiling on Android (it almost works)

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#28]
Hello.
Since I seem to like putting Scheme on all kinds of embedded devices, I tried compiling STklos on Android.
What follows is a draft of what could be a `INSTALL-android.md` file (but it doesn't work yet).

I'd like to start working on this, if there is interest.

# Installing STklos on Android

Instead of cross-compiling, compile in Termux, which has all build tools available.
This means the following is needed:

- The user must have developer access and enable ADB debugging
- The Termux package must be installed on the device

The steps to install STklos are described below.

## Install adb on the build machine

The compilation is done on a different machine, which we'll call the build machine.

```
apt install adb
```

You will need to enable debugging in the Android device.

Test with a USB cable or Wifi (if you enabled ADB debugging
via Wifi):

* `adb devices` should list your Android device (you will need to authorize the connection on the device screen)
* `adb shell` gives you a shell on the device.

## Set sshd in Termux

Open Termux in the Android device and prepare it to accept 
ssh connections:

```
pkg install openssh
mkdir .ssh
cat > .ssh/authorized_keys
```

Paste your public ssh key there.

Now fix the permissions on `.ssh` and `.ssh/authorized_keys`:

```
chmod 600 .ssh/authorized_keys
chmod 700 .ssh
```

Termux does not start anything automatically, so every time we connect,
we need to call `sshd`:

```
sshd
```

## From the host:

ADB can forward the TCP port 8022 to the devices' 8022 port (which is where Termux's sshd listens by default):

```
adb forward tcp:8022 tcp:8022
ssh localhost -p 8022
```

And you should be in a Termux shell, via ADB.

## Back to Tmux now

After ssh'ing into the device, install the build tools (This will install Perl and other large packages as dependencies!)
Termux does not have gcc, only clang.

```
pkg install libgc make clang git autoconf automake
```

Configure: we need STklos' own copy of PCRE; using the system version
doesn't seem to work, and not use threads, because clang doesn't seem to find `pthread_cancel`:

```
./configure --with-provided-regexp --threads=none
make
```

## Problems

* In `process.c`, the macro `NOFILES` is used, but it is not recognized by the compiler (Clang 9).
  It seems to not be standard, and at least one header file mentions that "users should not use NOFILE". An alternative seems to be `RLIMIT_NOFILE`; changed this.

* Build doesn't finish, although the `stklos` binary is
produced in `src/`:

```
Making all in pkgman
make[1]: Entering directory '/data/data/com.termux/files/home/STklos/pkgman'
../utils/tmpgenlex lang-bigloo.l lang-bigloo.inc lang-bigloo
**** Error while executing file "../utils/stklos-genlex"
	 Where: in open-output-file
	Reason: could not open file `"/tmp/stklos08849-00000"'
```

It semes that STklos has the temp dir hardcoded (?)
On Termux, the variable `TMPDIR` is this:

```
$ echo $TMPDIR
/data/data/com.termux/files/usr/tmp
```

* FFI tests fail:

```
$ cd tests
$ make test
...
==== Testing FFI  ...                                            **** Error while executing file "do-test.stk"
	 Where: in %make-ext-func
	Reason: cannot find symbol `rindex' in `'

  - %make-ext-func
  - #[closure 7c5c073a40]
  - %execute
  - #[closure 7c5bdb5700]
  - call-with-values
  - #[closure 7c5c105100]
  - try-load
  - %try-load
  - %load
  - load-tests
  - ...
```

But if the FFI tests are commented out, all other tests pass.

**Comment by egallesio** [comment]
Waouh! It is really a terrific news. I'll try to fix all the points you have spotted and , thanks to the clear information you provide, it should be easy to correct most of them. I'll have a look to this in a couple of days.

**Comment by jpellegrini** [comment]
Hello @egallesio -- your recent changes made it possible to compile on Android!  :)

Note: for Termux, the configure line should be

```
./configure --with-provided-regexp --enable-threads=none --prefix=/data/data/com.termux/files/usr/
```

and you may run make without sudo.

Then STklos can be used inside Termux.

It may be possible to use STklos outside Termux, but it could be a little trickier, perhaps.

If the user has root access on the Android device,  STklos works:

```
# /data/data/com.termux/files/usr/bin/stklos
Warning: cannot create configuration directory "/?.stklos"
0;1m  \    STklos version 1.40  (Id: 58dfbe0)
0;1m   \   Copyright (C) 1999-2020 Erick Gallesio <eg@unice.fr>
0;1m  / \  Université Côte d'Azur
0;1m /   \ [Linux-3.18.140-perf-g1b0d9102ccae-aarch64/none/readline/utf8]
stklos>
```

Without root access, it could be possible, but maybe not easy (because of the security policies in Android):

```
 $ ls -l data/data/com.termux/files/usr/bin/
ls: data/data/com.termux/files/usr/bin/: Permission denied
```

If you want, I may put together the instructions in a file (`INSTALL-Android.md` maybe?)

**Comment by egallesio** [comment]
> Hi @jpellegrini

> -- your recent changes made it possible to compile on Android! :)

Yes, it was a little bit intentionally :-) The work you start was really helpful for running STklos on Android (I must admit that I had no idea how to start such a port and I thought it would be more difficult than that). Thanks again for showing me the way to compile it on this platform.

>
> Note: for Termux, the configure line should be
>
> ```
> ./configure --with-provided-regexp --enable-threads=none --prefix=/data/data/com.termux/files/usr/
> ```

In fact, you can use the standard lib pcre (it has been split in two parts:`libpcre` and `libpcreposix`). Adding  `libpcreposix` to the list of prerequisite packages will do the trick.

About the threads, everything works now except `thread-terminate!` when you try to terminate a thread which is not the current one. This is due to the absence of `pthread_cancel`  in the Android `libpthread` library, as you see it. All the other things works without problem (hence the `running-os` extension to pass the tests ;-) ) :

As far as I have understood, it is not intended to add `pthread_cancel` to the standard threads library.
So we have 3 options:

1. do not implement the termination of a thread (except self termination) on Android and raise an error.  I have already implemented that (3 tests have been avoided with the `running-os` function)

2. implement our own `pthread_cancel` for Android. I have an implementation for that using the `SIGUSR2` signal but in some cases I have a deadlock and I have not yet understood how to avoid it.

3. Look at https://github.com/tux-mind/libbthread which seems to implement it (in a way not too much different to the solution I have now).

So for now ① is OK, ② is the solution I prefer (but it is not ready now) but ③ is perhaps a long term plan B if I fail with ②. More on that soon....

>
> If you want, I may put together the instructions in a file (`INSTALL-Android.md` maybe?)

That would be really **great** if you can do that.

**Comment by jpellegrini** [comment]
Hello!

Well, this is great!
I'm working on the instructions.

Anyway -- you did not commit your alternative `pthread_cancel` yet, right? (On my phone I still need the `--threads=none` flag).

Also... For some reason, although STklos works, it cannot find its libraries, which _are_ installed:

```
stklos> (require "srfi-27")
**** Error:
load: cannot load file "srfi-27"
	(type ",help" for more information)
```

```
$ stklos-pkg
**** Error while executing file "/data/data/com.termux/files/usr/bin/stklos-pkg"
	 Where: in %vm-backtrace
	Reason: cannot load file "lex-rt"
```

```
$ ls -l  /data/data/com.termux/files/usr/share/stklos/1.40/lex-rt*
-rw-r--r-- 1 u0_a196 u0_a196 3865 Jun 28 07:41 /data/data/com.termux/files/usr/share/stklos/1.40/lex-rt.ostk
-rw-r--r-- 1 u0_a196 u0_a196 8988 Jun 28 07:41 /data/data/com.termux/files/usr/share/stklos/1.40/lex-rt.stk
$ ls -l  /data/data/com.termux/files/usr/share/stklos/1.40/srfi-27.*
-rw-r--r-- 1 u0_a196 u0_a196  8646 Jun 28 07:41 /data/data/com.termux/files/usr/share/stklos/1.40/srfi-27.ostk
-rw-r--r-- 1 u0_a196 u0_a196 22977 Jun 28 07:41 /data/data/com.termux/files/usr/share/stklos/1.40/srfi-27.stk
```

Why would STklos not find them? It seems that the load path is garbled:

```
stklos> (load-path)
("." "/data/data/com.termux/files/home?.stklos?pkg?lib" "/data/data/com.termux/files/home?.stklos?ext" "/data/data/com.termux/files/usr?share?stklos?1.40" "/data/data/com.termux/files/usr?lib?stklos?1.40")
(load-path '("."  "/data/data/com.termux/files/home/.stklos/pkg/lib" "/data/data/com.termux/files/home/.stklos/ext" "/data/data/com.termux/files/usr/share/stklos/1.40" "/data/data/com.termux/files/usr/lib/stklos/1.40"))
stklos> (require "srfi-27")
"srfi-27"
```

So the part of the paths which are not the prefix, but are appended to it (like `/pkg/lib`, `/share/stklos/1.40`) seem to be encoded in a way that did not translate correctly.

**Comment by jpellegrini** [comment]
Found it!
In `bonus.stk`, the `file-separator` definition doesn't list `android` as a possible running OS. This:

```
(define (file-separator)
  (case (running-os)
    ((unix cygwin-windows android)    #\/)
    ((windows)                        #\\)
    (else                             #\?)))
```

Fixes it.

**Comment by egallesio** [comment]
Hi, 
No, I have not committed the code concerning threads, since I'm still working on it.  
I have correct the `file-separator` bug. Thanks.

**Comment by egallesio** [comment]
Hi @jpellegrini,

I think tat everything is OK now for android. The current implementation of `thread-terminate!` on this platform is limited to the current thread (suicide) 
Implementation of a compatibility layer is possible. However, implies that we need  to keep a list of all the mutexes owned by the thread to be killed. This can be done but, since it implies a cost, even on OS with  `pthread_cancel` support, this solution has not been choose. I have spent several hours to track why I had sometimes a deadlock, and a complete correction for this platform is probably necessary.

**Comment by jpellegrini** [comment]
Great, it works!  Compilation and tests are fine, and stklos-pkg, stlkos-compile seem to work.
I'll make a PR with the README-android file.

**Comment by egallesio** [comment]
Maybe this issue can be closed. No?

**Comment by jpellegrini** [comment]
Yes!
