### ISSUE TITLE
Small problems in the manual

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#32]
These refer to the PDF manual, in `doc/pdf`

---

The example for `vector-copy`, on page 66, uses "string" when it should be "vector":

```
(vector-copy string start)
(vector-copy string start stop)
```

A leftover from copy/paste, I guess. :)

---

In the example for `socket-accept`, on page 128, the paragraph that starts with "The following example is a simple server" says the port used will be 12345, but the code uses port 13345.

---

Maybe it would also be nice to mention that the ports returned by the socket API are text ports, and not binary (of course the user can find out using a predicate, or deduce from the examples, but wouldn't it be better to be explicit?)

**Comment by jpellegrini** [comment]
If you tell me how to change thesource of the documentation, I could send PRs when I find problems.

**Comment by jpellegrini** [comment]
One more:
In page 108 of the PDF, it is said that `(machine-type)` result string is of the form `'(os-name)-'(os-version)-'(processor-type)`, but STklos does not implement a `(processor-type)` procedure. As I understand form the output, the manual should say  `'(os-name)-'(os-version)-'(cpu-architecture)`:

```
stklos> (machine-type)
"Linux-5.6.0-2-amd64-x86_64"
stklos> (cpu-architecture)
"x86_64"
stklos>
```

**Comment by egallesio** [comment]
I think I have corrected all the errors of this issue.

>Maybe it would also be nice to mention that the ports returned by the socket API are text ports, and not binary (of course the user can find out using a predicate, or deduce from the examples, but wouldn't it be better to be explicit?)

It was said in the documentation of `socket-xxxput-port` that the port was textual.  
However, I have changed the port to be textual AND binary. It will be simpler if the server is a pure data server. 

> If you tell me how to change the source of the documentation, I could send PRs when I find problems.

All the documentation is in the `doc/skb` directoy and in the sources. Changing the documentation is not too difficult, what is more tricky is building it. The documentation is written in [Skribe](https://www.stklos.net/~eg/Publis/JFP05/article.html) and running it is difficult even for me :-<  (Skribe works in an old version of STklos, and I making a docker image is on my todo list since a while).

**Comment by jpellegrini** [comment]
Hi @egallesio - thank you for explaining this.

I see that the documentation is fixed in the HTML, but it seems like the PDF still has the `(vector-copy string ...)` problem...

**Comment by egallesio** [comment]
I don't know what I have done. Ii should be OK now!

**Comment by jpellegrini** [comment]
Yes, it's fixed! :)
