### ISSUE TITLE
gtklos: cannot install on macosx (symbol not found in flat namespace '_g_free')

### ISSUE THREAD

**Issue by bentxt** [egallesio/STklos#353]
Hi,
I try to install gtklos on my macos Monterey 12.1 and run some examples.
I can work with gtk 2 and 3 with C. In the old gtklos-base-pkg you have included some examples in C and this examples also work.

First I build stklos from the latest release:
```
cd stklos-1.70 && ./configure && make
```

This works so I try to build `gtklos`
```
cd extensions/gtklos/src && make clean && make
```

This also works and I also can print the symbols

```
nm -g  gtklos.so | grep free
  U _g_free
                 U _g_slist_free
                 U _gdk_event_free
```

When I try to build a button in the ./demo directory, the following error 
```
make button
../../../utils/tmpcomp -o button button.stk
**** Error while executing file "../../../utils/stklos-compile.stk"
	 Where: in %file-informations
	Reason: cannot open object file ../src/gtklos.so (dlopen(../src/gtklos.so, 0x0009): symbol not found in flat namespace '_g_free')

  - %file-informations
  - <<let/call>>
  - find-file-informations
  - <<let/call>>
  - compile-require
  - #[closure 103c850a0]
  - <<let/call>>
  - include-file
  - #[closure 103c85230]
  - <<let/call>>
  - ...
Set shell variable STKLOS_FRAMES to set visible frames
EXIT
```

**Comment by egallesio** [comment]
Hi @bentxt, 

This is weird that you have a file suffixed by `.so`  on MacOS. That probably means that the building of the library is not correct. I will have a look at this issue.   
Thanks for signaling it.

**Comment by egallesio** [comment]
OK, GTklos didn't work anymore on Linux too with the new implementation of modules. I'll correct it fist on Linux, and will try to access an OSX machine to fix this issue.

**Comment by egallesio** [comment]
Hi @bentxt,

There were in fact two problems:  
- one related to the fact that OSX file system is case-insensitive by default
- and the problem about the loader, which doesn't find back the symbols of the core of STklos. This was due to the fact that we used the installed version of the `stklos` binary, which is stripped (not an issue on Linux).

Everything should be fixed now with the latest commit. You can run the demos in the `extension/gtklos` directory with `run-demos`. The demos don't use anymore a previous installation of STklos. However,  if you install `stklos`, the `<installdir>/bin/stklos`  will still be striped, which can be a concern, if you want to use GTK after that. In this case, you can use `make install-base-no-strip` for installing STklos.

**Comment by jpellegrini** [comment]
Hi @egallesio !
In my Debian machine I get this when trying to build gtklos:

```
$ make all
Making all in lib/stklos
make[1]: Entering directory '/home/jeronimo/pkg/scheme/STklos/extensions/gtklos/lib/stklos'
../../../../utils/tmpcomp -C -o gtklos-incl.c gtklos.stk
**** Error while executing file "../../../../utils/stklos-compile.stk"
	 Where: in error
	Reason: Cannot find GTK+ library file "libgtk-3"

  - error
  - find-gtk-library
  - #[closure 7feb5b64d370]
  - <<let/call>>
  - compile
  - #[closure 7feb5b64d410]
  - <<let/call>>
  - %include-file
  - for-each
  - compile-include
  - ...
Set shell variable STKLOS_FRAMES to set visible frames
EXIT
gcc -g -Wall -O2   -fpic -nostdlib \
         -pthread -I/usr/include/goocanvas-2.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 \
         -I../../../../src   \
         -c -o gtklos.o gtklos.c
gtklos.c:34:10: fatal error: gtklos-incl.c: No such file or directory
   34 | #include "gtklos-incl.c"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:585: gtklos.so] Error 1
make[1]: Leaving directory '/home/jeronimo/pkg/scheme/STklos/extensions/gtklos/lib/stklos'
make: *** [Makefile:382: all-recursive] Error 1
```

**Comment by jpellegrini** [comment]
And `libgtk-3-dev` is installed...

**Comment by egallesio** [comment]
> And `libgtk-3-dev` is installed...

This is probably not necessary, since the library is dynamically loaded. This implies that the GTK libraries must be in a standard place. A said in the README:


> *Important note:** The GTK libraries are searched in standard places (that is `/usr/lib` and `/usr/local/lib`). If your libraries are located elsewhere (use the `locate` command to have a hint), you can set the `STKLOS_GTK_DIR` environment variable. For instance, for a machine running Debian or Ubuntu on an x86_64 architecture, you'll probably have to do
> 
> ```shell
> $ export STKLOS_GTK_DIR=/usr/lib/x86_64-linux-gnu
> ```

I have tried in an Ubuntu VM, and it seems to work. I don't have a Debian VM ready, but I suppose that it should work. Please, can you tell me if it is the case @jpellegrini.

**Comment by jpellegrini** [comment]
Ooops!
Sorry, I missed that part of the README!
It is necessary every time we use `gtklos`, right?

**Comment by jpellegrini** [comment]
(And yes, it works when I set it to `/usr/lib/x86_64-linux-gnu/`

**Comment by bentxt** [comment]
Ok, I try to start from scratch with a fresh clone:

```
rm -rf stklos.git

git clone https://github.com/egallesio/STklos stklos.git

cd stklos.git

./configure && make 

cd extensions/gtklos && make clean && make
```



I still get this errors:

```
./../../utils/tmpcomp -o toolbar toolbar.stk
**** Error while executing file "../../../utils/stklos-compile.stk"
	 Where: in %file-informations
	Reason: cannot open object file ../lib/stklos/gtklos.so (dlopen(../lib/stklos/gtklos.so, 0x0009): symbol not found in flat namespace '_g_free')

  - %file-informations
  - <<let/call>>
  - find-file-informations
  - <<let/call>>
  - %grab-file-information
  - for-each
  - #[closure 10d634000]
  - <<let/call>>
  - compile
  - #[closure 10d5da2d0]
  - ...
Set shell variable STKLOS_FRAMES to set visible frames
EXIT
```

**Comment by egallesio** [comment]
Hello @bentxt, 

I don't understand. It is Ok for me with the same commands. Have you installed GTK+3 with brew? 
When running `run-demos` I have 
![image](https://user-images.githubusercontent.com/34247321/152593734-df093d4f-019e-4cc7-9146-ad90dfe1b84f.png)

**Comment by bentxt** [comment]
If you want to know how my machine is configured (libraries, compilers, etc) please let me know and please tell me the commands which I have to use (eg. gcc -v). I'll provide you with that info asap.

**Comment by egallesio** [comment]
I don't understand  the problem. 
You said: 
> ./../../utils/tmpcomp -o toolbar toolbar.stk
> **** Error while executing file "../../../utils/stklos-compile.stk"
>	 Where: in %file-informations
>	Reason: cannot open object file ../lib/stklos/gtklos.so (dlopen(../lib/stklos/gtklos.so, 0x0009): symbol not found in flat namespace '_g_free')

You were into the demo directory? The message seems to say that the file `extensions/gtklos/lib/stklos/gtklos.so` doesn't' t exist? Can you verify and possibly try to call make in this directory to create it, if it doesn't exist? 

Otherwise, I have tested on a fresh container with only a Catalina version on which I have only installed  all the needed libraries with brew (libffi, libgmp, bdw-gc and pcre) to avoid compiling them and gtk+3. 
I have no other package installed. The compiler used is the standard one (called with `gcc` but which is in fact  `clang` version 12.0.0).

**Comment by ryandesign** [comment]
> This is weird that you have a file suffixed by `.so` on MacOS

It's what you're telling it to do:

https://github.com/egallesio/STklos/blob/590c727038b2790ff047008035072f031eb399d3/utils/shlib-options#L161-L168

[Apple wants you to use the extension ".bundle"](https://stackoverflow.com/questions/2339679/what-are-the-differences-between-so-and-dylib-on-macos/2339910#2339910) for loadable modules / bundles but many other projects use the ".so" extension for this on macOS and that's fine.

**Comment by ryandesign** [comment]
> The message seems to say that the file `extensions/gtklos/lib/stklos/gtklos.so` doesn't' t exist?

No, the message says that the file `extensions/gtklos/lib/stklos/gtklos.so`, which exists, cannot be loaded because it refers to a symbol `_g_free` which was not found.

This problem remains for me, as originally reported, with the current code in master today. I'm on macOS 12, with dependencies provided by MacPorts instead of Homebrew. (That difference may be relevant, because Homebrew on Intel installs into /usr/local, whereas Homebrew on Apple Silicon installs into /opt/homebrew and MacPorts on all architectures installs by default into /opt/local. /usr/local is a standard directory that the operating system looks in; the others aren't.)

The symbol `_g_free` is of course provided by libglib-2.0.dylib but you're not linking with that nor the other libraries you want to use; you're expecting to be able to load those libraries at runtime. Maybe it is possible to make that work, but [trying to load dynamic libraries* at runtime is not recommended on macOS](https://stackoverflow.com/questions/73924174/how-to-get-dylibs-in-opt-local-lib-to-be-recognized-by-dlopen-in-macos-monterey#answer-73931251) and you're creating a lot of unnecessary work for yourself in trying to do so. Just link with the libraries you want normally at link time (like you do in the curl and fuse extensions) as in the following patch. (This applies to dynamic libraries (like libffi.dylib, libgmp.dylib, etc.), not loadable modules / bundles (like your gtklos.so); you're welcome to `dlopen` your own loadable modules / bundles, but if those bundles want to use dynamic libraries, they should link with those dynamic libraries at link time.)

```diff
--- a/configure.ac
+++ b/configure.ac
@@ -450,6 +450,7 @@ AC_RUN_IFELSE([AC_LANG_SOURCE([[ int inner (char *foo) { char bar; return !(foo
 ## --- GTKLOS

 GTK_CFLAGS=""
+GTK_LIBS=""
 HAVE_GTK=0
 HAVE_CANVAS=0
 GOOCANV=absent
@@ -459,6 +460,7 @@ GOOVERS=""
 if ${PKGCONFIG} --exists gtk+-3.0
 then
   GTK_CFLAGS=`${PKGCONFIG} --cflags gtk+-3.0`
+  GTK_LIBS=`${PKGCONFIG} --libs gtk+-3.0`
   HAVE_GTK=1
 fi

@@ -476,6 +478,7 @@ fi
 if test "X${GOOVERS}" != "X"
 then
    GTK_CFLAGS=`${PKGCONFIG} --cflags ${GOOVERS}`
+   GTK_LIBS=`${PKGCONFIG} --libs ${GOOVERS}`
    HAVE_GTK=1
    HAVE_CANVAS=1
    GOOCANV=present
@@ -633,6 +636,7 @@ AC_SUBST(ASCIIDOCTOR)
 AC_SUBST(HAVE_GTK)
 AC_SUBST(HAVE_CANVAS)
 AC_SUBST(GTK_CFLAGS)
+AC_SUBST(GTK_LIBS)
 AC_SUBST(GOOCANV)
 AC_SUBST(GOOVERS)

--- a/extensions/gtklos/lib/stklos/Makefile.am
+++ b/extensions/gtklos/lib/stklos/Makefile.am
@@ -66,7 +66,7 @@ SUFFIXES = .stk -incl.c .@SH_SUFFIX@ .c
          $(GTKFLAGS) \
          -I$(BASEDIR)/src @GCINC@ @GMPINC@ \
          -c -o $*.o $*.c
-       @SH_LOADER@ @SH_LOAD_FLAGS@  -o $*.@SH_SUFFIX@ $*.o @DLLIBS@
+       @SH_LOADER@ @SH_LOAD_FLAGS@  -o $*.@SH_SUFFIX@ $*.o @DLLIBS@ $(GTK_LIBS)
        /bin/rm -f $*.o

 $(EXTENSION)-incl.c: $(EXTENSION).stk $(SCM_SRCS)
```

After applying that patch and running `autoreconf`, building the extension still fails:

```
% make
Making all in lib/stklos
../../../../utils/tmpcomp -C -o gtklos-incl.c gtklos.stk
*** Error while compiling: Cannot find GTK+ library file "libgtk-3"
Backtrace:
  - error
  - find-gtk-library
  - #[closure 1104bd500]
  - <<let/call>>
  - compile
  - #[closure 110208640]
  - <<let/call>>
  - %include-file
  - for-each
  - compile-include
  - ...
Set shell variable STKLOS_FRAMES to set visible frames
Trying to output file... Done.
make[1]: *** [gtklos-incl.c] Error 255
make: *** [all-recursive] Error 1
%
```

Setting `STKLOS_GTK_DIR` fixes it:

```
% export STKLOS_GTK_DIR=/opt/local/lib
% make
Making all in lib/stklos
../../../../utils/tmpcomp -C -o gtklos-incl.c gtklos.stk
widgets/image.stk:70: warning: reference to undefined symbol %guess-pathname
cc -Os   -fPIC -fno-common \
         -I/opt/local/include/goocanvas-2.0 -I/opt/local/include/gtk-3.0 -I/opt/local/include/at-spi2-atk/2.0 -I/opt/local/include/at-spi-2.0 -I/opt/local/include -I/opt/local/include/dbus-1.0 -I/opt/local/lib/dbus-1.0/include -I/opt/local/include -I/opt/local/include/gtk-3.0 -I/opt/local/include/gio-unix-2.0 -I/opt/local/include -I/opt/local/include/cairo -I/opt/local/include -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include/pango-1.0 -I/opt/local/include/fribidi -I/opt/local/include -I/opt/local/include/harfbuzz -I/opt/local/include -I/opt/local/include/atk-1.0 -I/opt/local/include/cairo -I/opt/local/include/gdk-pixbuf-2.0 -I/opt/local/include -I/opt/local/include/cairo -I/opt/local/include -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/pixman-1 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/libpng16 -I/opt/local/include \
         -I../../../../src -I/opt/local/include  \
         -c -o gtklos.o gtklos.c
cc -bundle -flat_namespace -undefined suppress  -o gtklos.so gtklos.o  -L/opt/local/lib -lgoocanvas-2.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lcairo
/bin/rm -f gtklos.o
Making all in demos
../../../utils/tmpcomp -o demos demos.stk
../../../utils/tmpcomp -o button button.stk
../../../utils/tmpcomp -o canvas1 canvas1.stk
../../../utils/tmpcomp -o canvas2 canvas2.stk
../../../utils/tmpcomp -o canvas3 canvas3.stk
../../../utils/tmpcomp -o canvas4 canvas4.stk
../../../utils/tmpcomp -o canvas5 canvas5.stk
../../../utils/tmpcomp -o checkbutton checkbutton.stk
../../../utils/tmpcomp -o colorchooser colorchooser.stk
../../../utils/tmpcomp -o combobox combobox.stk
../../../utils/tmpcomp -o dialog dialog.stk
../../../utils/tmpcomp -o entry1 entry1.stk
../../../utils/tmpcomp -o entry2 entry2.stk
../../../utils/tmpcomp -o entry3 entry3.stk
../../../utils/tmpcomp -o event event.stk
../../../utils/tmpcomp -o filechooser filechooser.stk
../../../utils/tmpcomp -o fontchooser fontchooser.stk
../../../utils/tmpcomp -o frame frame.stk
../../../utils/tmpcomp -o grid1 grid1.stk
../../../utils/tmpcomp -o grid2 grid2.stk
../../../utils/tmpcomp -o header header.stk
../../../utils/tmpcomp -o image1 image1.stk
../../../utils/tmpcomp -o image2 image2.stk
../../../utils/tmpcomp -o label label.stk
../../../utils/tmpcomp -o menu1 menu1.stk
../../../utils/tmpcomp -o menu2 menu2.stk
../../../utils/tmpcomp -o menu3 menu3.stk
../../../utils/tmpcomp -o progress progress.stk
../../../utils/tmpcomp -o radiobutton radiobutton.stk
../../../utils/tmpcomp -o scale scale.stk
../../../utils/tmpcomp -o scroll1 scroll1.stk
../../../utils/tmpcomp -o scroll2 scroll2.stk
../../../utils/tmpcomp -o sedit sedit.stk
../../../utils/tmpcomp -o separator separator.stk
../../../utils/tmpcomp -o text text.stk
../../../utils/tmpcomp -o toolbar toolbar.stk
make[1]: Nothing to be done for `all-am'.
%
```

And the demos then work. I suspect the code for loading libraries at runtime can then be removed to avoid the need to set `STKLOS_GTK_DIR`.

**Comment by egallesio** [comment]
This should be corrected thanks to @ryandesign indications in Issue #440. 
Closing the issue, but feel free to reopen it id necessary.
