### ISSUE TITLE
Change "short" to "int16_t"?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#355]
Hi @egallesio !

I was working on the serialization code which would be used in the new macro code, and noticed that the VM uses `short` for the opcodes. The result is portable bytecode, since in most usable platforms these days `short` is exactly two bytes!
But I was wondering if it wouldn't be a good idea to use `uint16_t`, for two reasons: first, it would make the code immediately clearer, and second, well, maybe someday we'll have a machine with `short int`s that are 32-bit wide? Then the byte code wouldn't be portable anymore.
What do you think?

**Comment by egallesio** [comment]
Hi @jpellegrini, 

I've avoided the fixed width integers at the beginning of STklos writing, because they were not present everywhere at this time.  This was 20 years before, and we can now assume that all the C99 feature can be uses without restrictions. 

Consequently, this is a very good idea to use them for the VM, and you are correct this would be clearer. 

Having a marshalling/unmarshalling for STklos would be great, and thanks for that. However, is it not possible to keep the macro source code instead of its bytecode to keep it in the .ostk file (as this is done  for legacy macros)?

BTW, if we have serialization of function, we can easily dream that we can migrate them to another machine ... A lot  of interesting stuff cans be derived from that...

**Comment by jpellegrini** [comment]
Ok, PR #357 is submitted! :)

**Comment by jpellegrini** [comment]
> is it not possible to keep the macro source code instead of its bytecode to keep it in the .ostk file (as this is done for legacy macros)?

Yes, sure!
But for files with a lot of macros it may become somewhat strange... A compiled file with lots of source code.

**Comment by jpellegrini** [comment]
@egallesio -- Since PR #357 was merged, I suppose this issue may can be closed. Do you agree?

**Comment by egallesio** [comment]
You are right. 
Done
