### ISSUE TITLE
Behavior of delay

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#41]
Hello,

According to R7RS, delay is supposed to be used to implement lazy evaluation - but it doesn't say it "must not" evaluate its argument... In page 19, it is said that implementations may do "implicit forcing" when "the value of a promise is forced by procedures that operate only on arguments of a certain type, like cdr and *. However, procedure that operate uniformly on their arguments, like list, must not force them"

Then the example is given:

```
(+ (delay (* 3 7)) 13)   ==> unspecified
(car (list (delay (* 3 7)) 13)) ==>  a promise
```

In STklos,

```
stklos> (delay (+ 1 "a"))
#[promise 7f303a221f20]

stklos> (+ (delay (* 3 7)) 13)
**** Error:
+: `#[promise 7f984ec18920]' is a bad number
	(type ",help" for more information)
```

Ok, so far it seems fine. Now,

```
stklos> (delay (/ 1  0))
**** Error:
/: cannot make rational with null denominator
	(type ",help" for more information)

stklos> (car (list (delay (/ 1 0)) 2))
**** Error:
/: cannot make rational with null denominator
	(type ",help" for more information)

stklos> (car (list (delay (* 3 7)) 13))
#[promise 7f9852d644a0]
```

I suppose this is an optimization, that would use a constant where there was a `(/ 1 0)`, right?
It seems to not be in line with the spec, because the expression substituted was inside a delay...

Or did I get something wrong?

(The same happens if I require SRFI-45 first)

This affects the implementation of SRFI-41.

**Comment by egallesio** [comment]
> I suppose this is an optimization, that would use a constant where there was a `(/ 1 0)`, right?

Yes it is. In fact, binary operations that can be computed at compile time are replaced by their result as you can see here
```scheme
tklos> (define (foo) (* 3 4))
;; foo
stklos> (disassemble foo)

000:  SMALL-INT            12
002:  RETURN              
003:
stklos> 
```
As you see the function returns 12 and does not do the computation at each call. This is a small optimization and it doesn't work yet  with n-ary usage of `+` . 

So, For STklos, the code `(/ 3 2)` is equivalent to 3/2. The example you gave `(delay (/ 1 0))` is in the 
R7RS document, but I don't like it because it forbids such (small) compiler optimizations. I think that the idea behind the R7RS is that `(delay (error "foo"))` must not call `error` immediately and produce an error when `error` is called (that is when the promise is forced). in the case of `(delay (/ 1 0))`, the `/` is not called at execution time. The following code shows that `/` is not called

```scheme
(let ((b 0)) (delay (/ 1 b)))
```
where a promise is computed (thanks to the fact that the STklos compiler is not able to do constant propagation ;-) )

> It seems to not be in line with the spec, because the expression substituted was inside a delay...

That's true, on this particular example, but I'm not too much enthusiast enough  to change the compiler just fo this example. 

> This affects the implementation of SRFI-41.

The implementation or som test?

**Comment by jpellegrini** [comment]
> I think that the idea behind the R7RS is that (delay (error "foo")) must not call error immediately and produce an error when error is called (that is when the promise is forced)

Is there a way around this? When is the error called? During the optimization? If so, would it be reasonable to catch error during the optimization phase, and ignore them (or have an option to turn them into warnings?)

> The implementation or some tests?

I forgot :) - I'll check again.
But even if the reference implementation uses it, we can adapt. :)

**Comment by jpellegrini** [comment]
Ok no problem - it was actually an example I used when I taught Scheme years ago. But it isn't necessary.
I'll submit a PR with SRFI-41 tomorrow!

**Comment by egallesio** [comment]
> Is there a way around this? When is the error called? During the optimization? If so, would it be reasonable to catch error during the optimization phase, and ignore them (or have an option to turn them into warnings?)
> 

I have tried, and was not able to find another example, where you don't want that `(/ 1 0)` is considered as equivalent to `1/0`. In fact this is just what does this optimization. No Scheme that I know admits `(delay 1/0)` as a correct expression, since the reader does not accept `1/0` as a valid number. In STklos, it is the optimization phase  which considers that there is a problem, but we can imagine a Scheme where it is the reader that  converts `(/ a b)` in `a/b`  if `a` and `b` are integers and `/` is still bound to the division. 

I think it's a great deal to add such an option for this (isolated?)  case.

**Comment by jpellegrini** [comment]
You're right... Sorry for the noise! I believe we can close this, then?

**Comment by egallesio** [comment]
No problem at all
I close it.
