### ISSUE TITLE
Small typo in documentation

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#43]
In the manual and SUPPORTED-SRFIs, "Transducers" is missing the "a":

```
$ grep -r Trn *
doc/html/stklos-ref-14.html: <tr><td valign="top" align="left"></td><td colspan="4" width="100%"><a href="stklos-ref-14.html#SRFI-171----Trnsducers">SRFI-171 -- Trnsducers</td></tr>
doc/html/stklos-ref-14.html:<p>in your code or uses the <code>cond-expand</code> special form.</p></div></div><a name="--index-entry-51209"></a><div class="sectiondiv"><div class="sectiontitle"><a name="SRFI-171----Trnsducers"></a>
doc/html/stklos-ref-14.html:<h3 id="SRFI-171----Trnsducers">SRFI-171 -- Trnsducers</h3>
SUPPORTED-SRFIS:    - SRFI-171: Trnsducers
```

But I don't know how  to fix it (I was hoping that the grep command above would show me where in the source it was typed wrong, so I could fix it, but it only detects `SUPPORTED-SRFIS` and `stklos-ref-14.html`.)

**Comment by egallesio** [comment]
I have seen it and corrected it this morning, and I will commit that soon. The error comes from the file `doc/skb/srfi.stk`. But I have to rebuild the documentation to propagate the correction everywhere. Since the documentation use my old version of Skribe, it is not rebuilt when you do a make at the toplevel (it is only built when you are in the `skb` directory).

**Comment by jpellegrini** [comment]
Ah ok, I see the fix was pushed. Closing...
