### ISSUE TITLE
Mac build issues

### ISSUE THREAD

**Issue by lassik** [egallesio/STklos#440]
The following are excerpts from a Mac build of the current git master. The build succeeds, but these probably mean that some features don't work.

```
gcc -DHAVE_CONFIG_H -I.   -I/usr/local/Cellar/pcre/8.45/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/ffi -I/usr/local/Cellar/bdw-gc/8.2.2/include   -g -O2 -MT vm.o -MD -MP -MF .deps/vm.Tpo -c -o vm.o vm.c
vm.c:1954:32: warning: unknown warning group '-Wdangling-pointer', ignored
      [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wdangling-pointer"
                               ^
1 warning generated.


gcc -DHAVE_CONFIG_H -I.   -I/usr/local/Cellar/pcre/8.45/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/ffi -I/usr/local/Cellar/bdw-gc/8.2.2/include   -g -O2 -MT vm.o -MD -MP -MF .deps/vm.Tpo -c -o vm.o vm.c
vm.c:1954:32: warning: unknown warning group '-Wdangling-pointer', ignored
      [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wdangling-pointer"
                               ^
1 warning generated.


../../utils/tmpcomp -o 19.ostk 19.stk
19.stk:1027: warning: reference to undefined symbol time-zone-name
19.stk:887: warning: reference to undefined symbol %leap-second-delta
19.stk:554: warning: reference to undefined symbol %time-utc->time-tai!
19.stk:527: warning: reference to undefined symbol %time-tai->time-utc!


../../utils/tmpcomp -C -o 238-incl.c 238.stk
238.stk:126: warning: reference to undefined symbol %create-system-codesets!
238.stk:96: warning: reference to undefined symbol %make-user-codeset
238.stk:64: warning: reference to undefined symbol %codeset-message
238.stk:64: warning: reference to undefined symbol %find-codeset
238.stk:59: warning: reference to undefined symbol %codeset-symbols


../utils/tmpcomp -o slib.ostk slib.stk
**** Error while executing command ("../utils/stklos-compile.stk" "--no-time" "--output=slib.ostk" "slib.stk")

EXIT
../utils/tmpcomp -o tar.ostk tar.stk
tar.stk:41: warning: reference to undefined symbol define-condition-type
tar.stk:42: warning: reference to undefined symbol &tar-error?
tar.stk:41: warning: reference to undefined symbol &tar-error


Making all in pkgman
../utils/tmpgenlex lang-bigloo.l lang-bigloo.inc lang-bigloo
../utils/tmpgenlex lang-chicken.l lang-chicken.inc lang-chicken
../utils/tmpgenlex lang-mzscheme.l lang-mzscheme.inc lang-mzscheme
../utils/tmpcomp -o stklos-pkg main.stk
main.stk:158: warning: reference to undefined symbol &error-pkg
warning: reference to undefined symbol define-condition-type
warning: reference to undefined symbol &error-pkg?


../utils/tmpgenlex lang-mzscheme.l lang-mzscheme.inc lang-mzscheme
../utils/tmpcomp -o stklos-pkg main.stk
main.stk:158: warning: reference to undefined symbol &error-pkg
warning: reference to undefined symbol define-condition-type
warning: reference to undefined symbol &error-pkg?


../utils/tmpgenlex lang-bigloo.l lang-bigloo.inc lang-bigloo
../utils/tmpgenlex lang-chicken.l lang-chicken.inc lang-chicken
../utils/tmpgenlex lang-mzscheme.l lang-mzscheme.inc lang-mzscheme
../utils/tmpcomp -o stklos-pkg main.stk
main.stk:158: warning: reference to undefined symbol &error-pkg
warning: reference to undefined symbol define-condition-type
warning: reference to undefined symbol &error-pkg?
```

**Comment by egallesio** [comment]
Oops. I have some homework. 
However, the `make tests` should be OK. 
Thanks for signaling those issues.

**Comment by egallesio** [comment]
I think that this is OK (at least on Catalina).

**Comment by lassik** [comment]
Great, thanks! I can confirm that the build now produces no warnings on Catalina.

**Comment by lassik** [comment]
However, loading shared libraries doesn't seem to work on this OS. (It works fine on Linux.) Some examples:

```
stklos> (import (srfi 160))
dyld: lazy symbol binding failed: Symbol not found: _STk_intern
  Referenced from: /.../lib/stklos/1.70/srfi/160/base.so
  Expected in: flat namespace

dyld: Symbol not found: _STk_intern
  Referenced from: /.../lib/stklos/1.70/srfi/160/base.so
  Expected in: flat namespace

**** Error:
%default-signal-handler: Received a SIGABRT signal.
	(type ",help" for more information)
```

```
stklos> (import (srfi 175))
dyld: lazy symbol binding failed: Symbol not found: _STk_read_from_C_string
  Referenced from: /.../lib/stklos/1.70/srfi/175.so
  Expected in: flat namespace

dyld: Symbol not found: _STk_read_from_C_string
  Referenced from: /.../lib/stklos/1.70/srfi/175.so
  Expected in: flat namespace

**** Error:
%default-signal-handler: Received a SIGABRT signal.
	(type ",help" for more information)
```

```
stklos> (import (srfi 238))
**** Error:
%file-informations: cannot open object file /.../lib/stklos/1.70/srfi/238.so (dlopen(/.../lib/stklos/1.70/srfi/238.so, 9): Symbol not found: _STk_errno_names
  Referenced from: /.../lib/stklos/1.70/srfi/238.so
  Expected in: flat namespace
 in /.../lib/stklos/1.70/srfi/238.so)
	(type ",help" for more information)
```

**Comment by egallesio** [comment]
That is really weird (it works for me on my Catalina VM)

Have you tries a `make tests` in the installation directory? Does it complete without error? 
I have 

```sh
Making all in tests
Use "make test" for testing STklos.
make[1]: Nothing to be done for `all-am'.
(cd tests; /Library/Developer/CommandLineTools/usr/bin/make test)
==== Testing Numbers  ...                                        passed
==== Testing Keywords  ...                                       passed
==== Testing call/cc & dynamic-wind  ...                         passed
==== Testing String Ports (SRFI 6)  ...                          passed
==== Testing File Ports  ...                                     passed
==== Testing Threads  ...                                        passed
==== Testing Simple Hash tables  ...                             passed
==== Testing SRFIs  ...                                          
      1    2    4    5    9   13   15   17   19   25   26   27
     28   29   35   36   37   41   43   48   51   54   60   62
     64   70   74   87   89   94   95  100  113  116  117  118
    125  127  128  129  130  132  133  134  135  137  141  143
    144  151  154  156  158  160  161  162  169  171  173  174
    175  176  180  185  189  190  193  195  196  207  208  214
    215  216  217  219  221  223  224  228  229  230  233  236
    238                                                          passed
==== Testing libs  ...                                           passed
==== Testing JSON  ...                                           passed
==== Testing MD5 checksum  ...                                   passed
==== Testing Base64 functions  ...                               passed
==== Testing Boxes  ...                                          passed
==== Testing Regexps  ...                                        passed
==== Testing FFI  ...                                            passed
==== Testing Some R5RS Report examples  ...                      passed
==== Testing R7RS  ...                                           passed
==== Testing R7RS libraries  ...                                 passed
==== Testing Circular structures  ...                            passed
==== Testing Unicode Characters  ...                             passed
==== Testing Unmutability  ...                                   passed
==== Testing Macros  ...                                         passed
==== Testing Miscellaneous tests  ...                            passed
==== Testing R5RS pitfall  ...                                   passed
----------------------------------------------------------------------
Number of tests: 19784 (OK: 19784 Error: 0)
   Elapsed Time: 9122ms
*** End of tests ***
eg@Ericks-MacBook-Pro STklos %
```


In the installation directory:

```sh
$ src/stklos -I lib
  \    STklos version 1.70  (Id: e6b874c0)
   \   Copyright (C) 1999-2023 Erick Gallesio <eg@stklos.net>
  / \  [Darwin-19.5.0-x86_64/pthreads/libedit/utf8]
 /   \ Type ',h' for help
stklos> (import (srfi 160))
stklos> (import (srfi 175))
stklos> (import (srfi 238))
stklos> (codeset-number 'errno 'EBADF)
9
```

The paths `/.../lib/XXX` seem weird to me (but the loader seems to hav found the `.so` file). Doy ou have a value in `LD_LIBRARY_PATH` , `DYLD_LIBARY_PATH` or `DYLD_FALLBACK_LIBRARY_PATH`?

**Comment by ryandesign** [comment]
> ```
> stklos> (import (srfi 160))
> dyld: lazy symbol binding failed: Symbol not found: _STk_intern
>   Referenced from: /.../lib/stklos/1.70/srfi/160/base.so
>   Expected in: flat namespace
> 
> dyld: Symbol not found: _STk_intern
>   Referenced from: /.../lib/stklos/1.70/srfi/160/base.so
>   Expected in: flat namespace
> 
> **** Error:
> %default-signal-handler: Received a SIGABRT signal.
> 	(type ",help" for more information)
> ```

Are you running `stklos` from the src directory or one that has been installed with `make install` or `make install-base`?

When I use `make install` or `make install-base` I see a similar problem:

```
% stklos
  \    STklos version 1.70  (Id: 3bc8d1f9)
   \   Copyright (C) 1999-2023 Erick Gallesio <eg@stklos.net>
  / \  [Darwin-21.4.0-x86_64/pthreads/libedit/utf8]
 /   \ Type ',h' for help
stklos> (import (srfi 160))
**** Error:
try-load: cannot open object file /opt/local/lib/stklos/1.70/srfi/160/base.so (dlopen(/opt/local/lib/stklos/1.70/srfi/160/base.so, 0x0009): symbol not found in flat namespace '_STk_C_apply')
	(type ",help" for more information)
stklos> ^D
%
```

The problem is that `make install` and `make install-base` will `strip` the executable, thereby removing the symbols the loadable modules want to use.

The solution is to use `make install STRIP=no` or `make install-base STRIP=no` or `make install-base-no-strip`.

See https://github.com/egallesio/STklos/issues/353#issuecomment-1028125323.

**Comment by lassik** [comment]
@ryandesign Awesome, that solved my problem! Thank you once again for offering your rare Mac expertise.

**Comment by lassik** [comment]
Most people probably want to be able to load modules. If so, the `configure` script should make `STRIP=no` the default on Mac.

**Comment by ryandesign** [comment]
> Awesome, that solved my problem!

I'm glad that turned out to be it!

If you like, you can [install stklos with MacPorts](https://ports.macports.org/port/stklos). I updated it to version 1.70 today including fixes for this and other issues. The gtklos extension is also available in the [stklos-gtklos](https://ports.macports.org/port/stklos-gtklos) port.

If you prefer a development version newer than 1.70, you can install the [stklos-devel](https://ports.macports.org/port/stklos-devel) port. The gtklos extension is available in the [stklos-gtklos-devel](https://ports.macports.org/port/stklos-gtklos-devel) port and the curl extension is in the [stklos-curl-devel](https://ports.macports.org/port/stklos-curl-devel) port.

**Comment by ryandesign** [comment]
> the `configure` script should make `STRIP=no` the default on Mac.

Yeah it's weird. If people on Linux aren't having this problem then I guess `strip` does something different on macOS than it does on Linux?

In that case, one option is not to `strip` on macOS. Another option is to `strip` but instruct it to remove the symbols we want removed and to retain the symbols we want retained. The strip(1) manpage (copied below) has some discussion about how to do that by providing `strip` with a file containing the list of symbols to be kept. Is such a file, or such a list of symbols, already produced by the STklos build system somewhere?

<details>
<summary>strip(1) manpage</summary>

# strip(1) - remove symbols

Apple Inc., June 23, 2020

    strip [ option ] name ...

<a name="description"></a>

# Description

_strip_ removes or modifies the symbol table attached to the output of the assembler and link editor. This is useful to save space after a program has been debugged and to limit dynamically bound symbols.

_strip_ no longer removes relocation entries under any condition. Instead, it updates the external relocation entries (and indirect symbol table entries) to reflect the resulting symbol table. _strip_ prints an error message for those symbols not in the resulting symbol table that are needed by an external relocation entry or an indirect symbol table. The link editor _ld_(1) is the only program that can strip relocation entries and know if it is safe to do so.

When _strip_ is used with no options on an executable file, it checks that file to see if it uses the dynamic link editor. If it does, the effect of the _strip_ command is the same as using the **-u** and **-r** options. If the file does not use the dynamic link editor, the effect of _strip_ without any options is the same as using the **-s** option of _ld_(1). The options **-S,** **-x,** and **-X** have the same effect as the _ld_(1) options. The options to _strip_(1) can be combined to trim the symbol table to just what is desired.

You should trim the symbol table of files used with dynamic linking so that only those symbols intended to be external interfaces are saved. Files used with dynamic linking include executables, objects that are loaded (usually bundles), and dynamic shared libraries. Only global symbols are used by the dynamic linking process. You should strip all non-global symbols.

When an executable is built with all its dependent dynamic shared libraries, it is typically stripped with:

    % strip -u -r executable

which saves all undefined symbols (usually defined in the dynamic shared libraries) and all global symbols defined in the executable referenced by the dynamic libraries (as marked by the static link editor when the executable was built). This is the maximum level of striping for an executable that will still allow the program to run correctly with its libraries.

If the executable loads objects, however, the global symbols that the objects reference from the executable also must not be stripped. In this case, you should list the global symbols that the executable wants to allow the objects to reference in a file, and those global symbols are then saved when the executable is stripped. For example:

    % strip -u -r -s interface_symbols executable

where the file _interface_symbols_ would contain only those global symbols from the executable that the executable wants the loaded objects to have access to.

For objects that will be loaded into an executable, you should trim the symbol table to limit the global symbols the executable will see. This would be done with:

    % strip -s interface_symbols -u object

which would leave only the undefined symbols and symbols listed in the file _interface_symbols_ in the object file. In this case, _strip_(1) has updated the relocation entries and indirect symbol table to reflect the new symbol table.

For dynamic shared libraries, the maximum level of stripping is usually **-x** (to remove all non-global symbols).

<a name="stripping-files-for-use-with-runtime-loaded-code"></a>

# Stripping Files for Use with Runtime Loaded Code

Trimming the symbol table for programs that load code at runtime allows you to control the interface that the executable wants to provide to the objects that it will load; it will not have to publish symbols that are not part of its interface. For example, an executable that wishes to allow only a subset of its global symbols but all of the statically linked shared library's globals to be used would be stripped with:

    % strip -s interface_symbols -A executable

where the file _interface_symbols_ would contain only those symbols from the executable that it wishes the code loaded at runtime to have access to. Another example is an object that is made up of a number of other objects that will be loaded into an executable would built and then stripped with:

    % ld -o relocatable.o -r a.o b.o c.o
    % strip -s interface_symbols -u relocatable.o

which would leave only the undefined symbols and symbols listed in the file _interface_symbols_ in the object file. In this case _strip_(1) has updated the relocation entries to reflect the new symbol table.

<a name="options"></a>

# Options

The first set of options indicate symbols that are to be saved in the resulting output file.

* **-u**
  Save all undefined symbols. This is intended for use with relocatable objects to save symbols referred to by external relocation entries. Note that common symbols are also referred to by external relocation entries and this flag does not save those symbols.
* **-r**
  Save all symbols referenced dynamically.
* **-s** _filename_
  Save the symbol table entries for the global symbols listed in _filename_. The symbol names listed in _filename_ must be one per line. Leading and trailing white space are not part of the symbol name. Lines starting with # are ignored, as are lines with only white space.
* **-R** _filename_
  Remove the symbol table entries for the global symbols listed in _filename_. This file has the same format as the **-s** _filename_ option above. This option is usually used in combination with other options that save some symbols, **-S,** **-x,** etc.
* **-i**
  Ignore symbols listed in the **-s** _filename_ or **-R** _filename_ options that are not in the files to be stripped (this is normally an error).
* **-d** _filename_
  Save the debugging symbol table entries for each source file name listed in _filename_. The source file names listed in _filename_ must be one per line with no other white space in the file except the newlines on the end of each line. And they must be just the base name of the source file without any leading directories. This option works only with the _stab_(5) debugging format, it has no affect when using the DWARF debugging format.
* **-A**
  Save all global absolute symbols except those with a value of zero, and save Objective C class symbols. This is intended for use of programs that load code at runtime and want the loaded code to use symbols from the shared libraries (this is only used with NEXTSTEP 3.3 and earlier releases).
* **-n**
  Save all N_SECT global symbols. This is intended for use with executable programs in combination with **-A** to remove the symbols needed for correct static link editing which are not needed for use with runtime loading interfaces where using the **-s** _filename_ would be too much trouble (this is only used with NEXTSTEP 3.3 and earlier releases).

These options specify symbols to be removed from the resulting output file.

* **-S**
  Remove the debugging symbol table entries (those created by the **-g** option to _cc_(1) and other compilers).
* **-X**
  Remove the local symbols whose names begin with \`L'.
* **-T**
  The intent of this flag is to remove Swift symbols. It removes the symbols whose names begin with \`\_$S' or \`\_$s' only when it finds an \_\_objc_imageinfo section with and it has a non-zero swift version. The future the implementation of this flag may change to match the intent.
* **-N**
  In binaries that use the dynamic linker remove all nlist symbols and the string table. Setting the environment variable STRIP_NLISTS has the same effect.
* **-x**
  Remove all local symbols (saving only global symbols).
* **-c**
  Remove the section contents of a dynamic library creating a stub library output file.

And the last options:

* **-**
  Treat all remaining arguments as file names and not options.
* **-D**
  When stripping a static library, set the archive's SYMDEF file's user id, group id, date, and file mode to reasonable defaults. See the _libtool_(1) documentation for **-D** for more information.
* **-o** _output_
  Write the result into the file _output_.
* **-v**
  Print the arguments passed to other tools run by _strip_(1) when processing object files.
* **-no_uuid**
  Remove any LC_UUID load commands.
* **-no_split_info**
  Remove the LC_SEGMENT_SPLIT_INFO load command and its payload load.
* **-no_code_signature_warning**
  Don't warn when the code signature would be invalid in the output.
* **-arch** _arch_type_
  Specifies the architecture, _arch_type_, of the file for _strip_(1) to operate on when the file is a universal file. (See _arch_(3) for the currently know _arch_types_.) The _arch_type_ can be "all" to operate on all architectures in the file, which is the default.

<a name="see-also"></a>

# See Also

ld(1), libtool(1), cc(1)

<a name="examples"></a>

# Examples

When creating a stub library the **-c** and **-x** are typically used:

    strip -x -c libfoo -o libfoo.stripped

<a name="limitations"></a>

# Limitations

Not every layout of a Mach-O file can be stripped by this program. But all layouts produced by the Apple compiler system can be stripped.

</details>

**Comment by egallesio** [comment]
I have changed the behavior of `make-install` with the 2.00 release. Now, the binary is no more stripped. I have tested this new way to install the binary on a VM and I think that this issue is now resolved. 
Thanks for your analysis @ryandesign.
