### ISSUE TITLE
Need an R7RS module system... :)

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#65]
For example, SRFI-13shadoes some R7RS procedures. So, in the tests, when we `(require "srfi-13")`, those procedures are gone. but then STklos, *without restarting*, will go on and do other tests, and when it gets to R7RS tests, the `string-map` fails.

The workaround I found was to "put back" the original `string-map` after testing SRFI-13, but this could become hard to manage.

R7RS modules would help keeping everything more isolated.

How do I help with this?

**Comment by jpellegrini** [comment]
> the `string-map` fails

I meant "the `string-map` test fails"... Sorry!

**Comment by jpellegrini** [comment]
It actually seems it wouldn't he hard to implement R7RS modules using what STklos already has...

**Comment by jpellegrini** [comment]
If it's OK, I'm willing to try to get a working R7RS module system

**Comment by lassik** [comment]
IIRC @egallesio said he is working on this.

BTW, regarding the big `(features)` list,  R7RS specifies a neat extension to `cond-expand`. This:

```scheme
(cond-expand ((library (srfi 69)) 123))
```

will only produce `123` when a library named `(srfi 69)` is available for importing. Most SRFIs are implemented as their own library in R7RS implementations, so this can be used instead of adding lots of feature identifiers (at least for R7RS code).

**Comment by jpellegrini** [comment]
Ah, ok -- I'll wait for him to finish then!

**Comment by egallesio** [comment]
> R7RS modules would help keeping everything more isolated.

I think this is not true. In fact, STklos modules offers more or less the same isolation than R7RS libraries. The real problem is that we **do not** use  modules for the implementation of SRFIs (excepted the internal functions which are hidden to the user).

The origin of the way SRFIs are implemented in STklos, is historical. STk, the ancestor of STklos, was R3RS and then R4RS (yes I'm this old!).  At this time, whereas STk already had modules similar to the STklos ones, there was no modules yet in Scheme. Consequently, to be as compatible as possible, the load of a SRFI tried to not show it was in a module for all the function described in the SRFI document. Hence the structure of the implementation of a SRFI is

```scheme
(define-module SRFI-n
   (export x y z)

)

(select-module STklos)
(import SRFI-n)
(provide "srfi-n")
```

The `STklos` module being visible by all modules, this ensures the user has something which works without even knowing that we have/use modules. However, if we omit the `select-module` and `import` at the end of the file, the isolation would be complete.

Since times have changed, perhaps that we should no more use them in the implementations of new SRFIs. If we do that, old codes will need to be changed, since they will need to do an import. I'm not comfortable with introducing such a regression now.

Another solution, could be to not import the implementation module for new SRFIs  and add a third documentation phrase for this module: they must be required and imported. This is far from ideal, but I don't see how to ensure compatibility and avoid the SRFI functions with have a different behavior than the STklos (or other SRFI) ones.

The `make test` is a special case since it is a program which import nearly all the files in the `lib` directory. If we do not import the SRFI, the testing could be done as

```scheme
(require "srfi-n")
(define-module  test-SRFI-n
   (import SRFI-n)
   (test .....)
   (test .....))
```
What do you think?


BTW, Sorry for the old guy historical reminders.

**Comment by egallesio** [comment]
> The workaround I found was to "put back" the original string-map after testing SRFI-13, but this could become hard to manage.

Before choosing a new way to implement SRFIs, I suppose that shifting the `test-srfi` at the end in `do-test.stk` would work, since only the SRFI may introduce functions with a behavior which is different of STklos functions. 
It's hacky but it should works, no?

**Comment by jpellegrini** [comment]
Hi @egallesio !

> BTW, Sorry for the old guy historical reminders ;-)

No problem - I'm 47, so not exactly young :)

> old codes will need to be changed, since they will need to do an import

Old code will do `require`, and the semantics of require could stay the same... R7RS does not mention it!  It only talks about "`import`"...

Then, new code could do the same as always, `(require "srfi-13")`, or

```
(import (srfi :13))
```

to get SRFI-13 (and, if I understand R7RS correctly, this would also load the necessary files). Or even import or rename only parts of a SRFI. There are some recent SRFIs that seem to do that -- SRFI-130 for example, does

```
(import (except (scheme base)
                 string-map
                 string-for-each))
```

I think I saw similar `import`s being used... The way I found to do this in STklos was to manually rename the procedures, but it's kind of cumbersome. 

> If we do not import the SRFI, the testing could be done as

Yes!!! That would be great!

By the way, now that I think of it, I think it may be interesting to run each test suite twice:

1. isolated, importing only the modules it needs
2. with a "fully loaded STklos", importing all possible modules, in order to catch conflicts (if there are irreconciliable conflicts, then we don't load the conflicting module)

Do you think this is useful?

**Comment by jpellegrini** [comment]
> (if there are irreconciliable conflicts, then we don't load the conflicting module)

and document it, of course!

**Comment by jpellegrini** [comment]
> Old code will do require, and the semantics of require could stay the same... R7RS does not mention it! It only talks about "import"...

> Then, new code could do the same as always, (require "srfi-13"), or `(import (srfi :13))`

Ok, I think I need to complement what I said:

There are two different actions: one, find the file where a SRFI or module is; and two, load parts (or all) of a known (loaded) module into the current module. Right?

* `require` does (1)
* `import` only does (2), but not (1)
* because of the way SRFIs are implemented, `require`ing them will also perform (2).

The second point (`import` does not automatically load from disk) seems to be minority - as long as I could find, only STklos and SISC do this. But anyway, R7RS says nothing about that! :)

What I meant is,

* What about changing `import` so it will have the same syntax and semantics of R7RS (`only`, `except`, `rename`, `prefix`)? It would be backward-compatible, so long as I can see.

* What about making `import` automatically load the module from the load path, if needed? This does change the semantics, but I suppose would not break anything. I'm actually not sure about this.

* Then, the problem of not automatically import the module for future/past SRFIs would be solved! If someone needs only part of a module,  it is possible to use `import` to do so. And even old SRFIs could use the module system! An `(import (srfi :13))`, without any modifier clause, would just bring full SRFI-13, as does `require`!

**Comment by jpellegrini** [comment]
Hi @egallesio ! I think this one is don, right?

**Comment by egallesio** [comment]
> Hi @egallesio ! I think this one is don, right?

Yep. Closed.
